### PR TITLE
Build cpputest from sources

### PR DESCRIPTION
**Pull request by anttiylitokola**
[x] I confirm this contribution is my own and I agree to license it with Apache 2.0.
[x] I confirm the moderators may change the PR before merging it in.

### CODE REVIEW

**Comment by anttiylitokola** [comment]
run-unit-tests

**Comment by anttiylitokola** [comment]
run-unit-tests

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
run-unit-tests

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
run-unit-tests

**Comment by anttiylitokola** [comment]
run-unit-tests

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Review by teetak01 — APPROVED** [review]

**Comment by anttiylitokola** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Pull request merged**
